import { getTotalRiskExposure, formatCurrency } from './riskCalculation'

function formatTime(seconds) {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

export function generateReport(findings, maintenance) {
  const [riskMin, riskMax] = getTotalRiskExposure(findings)
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const severityOrder = ['critical', 'high', 'moderate', 'low']
  const severityLabel = { critical: 'CRITICAL', high: 'HIGH', moderate: 'MODERATE', low: 'LOW' }

  const grouped = {}
  for (const sev of severityOrder) {
    grouped[sev] = findings.filter(f => f.severity === sev)
  }

  const counts = severityOrder
    .filter(s => grouped[s].length > 0)
    .map(s => `${grouped[s].length} ${severityLabel[s]}`)
    .join(', ')

  let report = `# VoltHawk Transmission Line Inspection Report

**Date:** ${date}
**Total Findings:** ${findings.length} (${counts})
**Estimated Risk Exposure:** ${formatCurrency(riskMin)} – ${formatCurrency(riskMax)}

---

`

  for (const sev of severityOrder) {
    if (grouped[sev].length === 0) continue
    report += `## ${severityLabel[sev]} Findings (${grouped[sev].length})\n\n`
    for (const f of grouped[sev]) {
      report += `### Finding #${f.id} — ${f.anomaly_type.replace(/_/g, ' ')}\n\n`
      report += `| Field | Detail |\n`
      report += `|-------|--------|\n`
      report += `| **Time Range** | ${formatTime(f.start_time)} – ${formatTime(f.end_time)} |\n`
      report += `| **Anomaly Type** | ${f.anomaly_type.replace(/_/g, ' ')} |\n`
      report += `| **Marengo Score** | ${f.marengo_score} |\n`
      report += `| **NERC Reference** | ${f.nerc_reference} |\n`
      report += `| **Priority** | ${f.priority_hours} hours |\n\n`
      report += `**Condition:** ${f.condition || f.query_used}\n\n`
      report += `**Recommended Action:** ${f.recommended_action}\n\n`
      report += `---\n\n`
    }
  }

  const escalations = maintenance
    .filter(m => (m.maintenance_status === 'deferred' || m.maintenance_status === 'overdue') && m.linked_finding_id)
    .map(m => ({ ...m, finding: findings.find(f => f.id === m.linked_finding_id) }))
    .filter(e => e.finding)

  if (escalations.length > 0) {
    report += `## Escalated Findings\n\n`
    for (const e of escalations) {
      report += `- **Tower ${e.tower_id}** (Finding #${e.finding.id}): ${e.maintenance_status} maintenance, last inspected ${e.last_inspection}. Visual anomaly: ${e.finding.anomaly_type.replace(/_/g, ' ')} (${e.finding.severity}). Immediate priority upgrade recommended.\n`
    }
    report += `\n---\n\n`
  }

  report += `*Generated by VoltHawk — TwelveLabs Marengo 3.0 + Pegasus 1.2 | NERC FAC-003-4 / FAC-501-3 / NESC Rule 215*\n`

  const blob = new Blob([report], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `volthawk-report-${new Date().toISOString().slice(0, 10)}.md`
  a.click()
  URL.revokeObjectURL(url)
}
